Fix build error on systems providing reallocarray.
My libc version provides 'reallocarray', but the libbpf code defaults
to using its local version when the .cc files and .h files are used directly.

This causes the error below. libbpf comes with scripts to detect if reallocarray
is provided or not.

In this change:
- change the BUILD configuration so that it invokes the build scripts
  of libbpf, which will directly detect the capabilities of the libc,
  and define or not reallocarray accordingly.
- also, fixed libbpf to depend on updated elfutils target.

In file included from external/libbpf/src/libbpf.c:41:
external/libbpf/include/tools/libc_compat.h:11:21: error: static declaration of 'reallocarray' follows non-static declaration
static inline void *reallocarray(void *ptr, size_t nmemb, size_t size)
                    ^
/usr/include/stdlib.h:558:14: note: previous declaration is here
extern void *reallocarray (void *__ptr, size_t __nmemb, size_t __size)
             ^